### ISSUE TITLE
博主，你好，可以请教一下你是如何给这个博客添加目录的吗？

### ISSUE THREAD

**Issue by zwyyy456** [chenkai0520/chenkai0520.github.io#1]

**Comment by ckvv** [comment]
你可以参考这个函数的写法, 原理就是遍历文章的`h1[id],h2[id],h3[id],h4[id]` ,然后生成目录
https://github.com/ckvv/ckvv.github.io/blob/main/static/js/custom.js#L147C1-L171C2
